version: "3"

services:
    backend:
        build:
            context: ./backend
        container_name: live_search_backend
        network_mode: host
        environment:
            - PORT=3333
    frontend:
        build:
            context: ./frontend
        container_name: live_search_frontend
        network_mode: host
        environment:
            - PORT=3334